[package]
name = "grafgrep"
version = "0.1.0"
edition = "2021"
license = "MIT"
description = "A super simple grep built for educational purpose"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
